workspace:
  path: src

pipeline:

  run-lint:
    group: pre-commit
    image: alpine:latest
    pull: true
    commands:
        - PATH=$PATH:/drone/src/google-cloud-sdk/bin
        - echo ${GCLOUD_SERVICE_KEY} >> /drone/src/drone.json
        - ls -las /drone/src/drone.json
        - cat /drone/src/drone.json
        # - apk add --update python tar python-dev py-pip build-base curl zip bash
        # - FILE_UUID=="test-test"
        # - curl https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz > gcloud.tar.gz
        # - tar -xvzf ./gcloud.tar.gz
        # - bash ./google-cloud-sdk/install.sh -q
        # - source /drone/src/google-cloud-sdk/path.bash.inc
        # - echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=/drone/src/drone.json
        # - gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        # - gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
        # - bash ./windows-packer/build.sh
        # - source /drone/src/google-cloud-sdk/path.bash.inc && gsutil -m cp /tmp/${FILE_UUID}.txt gs://${ARTIFACT_BUCKET}/${FILE_UUID}.txt
